import Head from 'next/head'
import { gql } from '@apollo/client'
import client from '../../apollo-client'
import Pdp from '../../components/Pdp/Pdp'

const Product = ({ product }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Pdp product={product}></Pdp>
    </>
  )
}

export default Product

export async function getServerSideProps(context) {
  debugger
  const slug = context.params.slug
  const { data } = await client.query({
    query: gql`
        query Products {
            product(channel: "uk", slug: "${slug}" ) {
                id
                name
                slug
                seoTitle
                thumbnail {
                    url
                }
                description
                pricing {
                    priceRange {
                        start {
                            gross {
                                amount
                                currency
                            }
                        }
                        stop {
                            gross {
                                amount
                                currency
                            }
                        }
                    }
                }
            }
        }
        `,
  })

  return {
    props: {
      product: data.product,
    },
  }
}
